DROP TABLE IF EXISTS AGENDA_ARCHIVE CASCADE;
DROP TABLE IF EXISTS ACTIVITE_ARCHIVE CASCADE;
DROP TABLE IF EXISTS AGENDA_POSSEDE_PAR_UTILISATEUR CASCADE;
DROP TABLE IF EXISTS INVITATION_ACTIVITE CASCADE;
DROP TABLE IF EXISTS NOTATION CASCADE;
DROP TABLE IF EXISTS INSCRIPTION CASCADE;
DROP TABLE IF EXISTS LIKER CASCADE;
DROP TABLE IF EXISTS SABONNER CASCADE;
DROP TABLE IF EXISTS CATEGORIE_AGENDA CASCADE;
DROP TABLE IF EXISTS CATEGORIE CASCADE;
DROP TABLE IF EXISTS COMMENTAIRE CASCADE;

DROP TABLE IF EXISTS ACTIVITE CASCADE;
DROP TABLE IF EXISTS AGENDA CASCADE;
DROP TABLE IF EXISTS UTILISATEUR CASCADE;